### PR TITLE
Fix broken equality test when age is undefined

### PR DESCRIPTION
**Pull request by zyegfryed**

### CODE REVIEW

**Comment by kirsle** [comment]
What was broken about that code? When age == undefined, none of the conditions should match so the `-Reply` at the end would be given.

**Comment by zyegfryed** [comment]
Hi @kirsle 
I'm afraid this is not what I'm experiencing, as shown in the following transcript:

```
$ rlwrap rivescript tmp
RiveScript Interpreter - Interactive Mode
-----------------------------------------
RiveScript Version: v2.0.2
        Reply Root: tmp

You are now chatting with the RiveScript bot. Type a message and press Return to send it.
When finished, type '/quit' to exit the program. Type '/help' for other options.

You> what am i old enough to do?
Argument "undefined" isn't numeric in numeric gt (>) at /Users/zyegfryed/perl5/lib/perl5/RiveScript.pm line 2722, <STDIN> line 1.
Argument "undefined" isn't numeric in numeric gt (>) at /Users/zyegfryed/perl5/lib/perl5/RiveScript.pm line 2722, <STDIN> line 1.
Argument "undefined" isn't numeric in numeric gt (>) at /Users/zyegfryed/perl5/lib/perl5/RiveScript.pm line 2722, <STDIN> line 1.
Argument "undefined" isn't numeric in numeric lt (<) at /Users/zyegfryed/perl5/lib/perl5/RiveScript.pm line 2712, <STDIN> line 1.
Bot> You're not old enough to do much of anything yet.
```

Is that a bug?

**Comment by zyegfryed** [comment]
FYI the previous comment was relying on the Perl interpreter.

Have some warnings with the Go one, as you can see below:

```
 $ rlwrap ./bin/rivescript tmp
RiveScript Interpreter (Golang) -- Interactive Mode
---------------------------------------------------
RiveScript version: 0.0.2
        Reply root: tmp

You are now chatting with the RiveScript bot. Type a message
and press Return to send it. When finished, type '/quit' to
exit the program. Type '/help' for other options.
You> what am i old enough to do?
[WARN] Failed to evaluate numeric condition!
[WARN] Failed to evaluate numeric condition!
[WARN] Failed to evaluate numeric condition!
[WARN] Failed to evaluate numeric condition!
Bot> I don't know how old you are.
You>
```

**Comment by kirsle** [comment]
Cool. I think this is a bug in all the interpreters (it should probably check if the comparison is valid before attempting it), but in the mean time the tutorial should be fixed so as not to expose the bug to newbies. :wink:

**Pull request merged**
